name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: testing-deployment-with-azure
      AZURE_RESOURCE_GROUP: testing-deployment-with-azure
      GH_REPO: paudel.prashant/testing-deployment-with-azure

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        if: runner.os == 'Linux'

      - name: Check Azure CLI Version
        run: |
          az --version
          az upgrade --yes
        if: runner.os == 'Linux'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: AZUREAPPSERVICE_PUBLISHPROFILE_TESTING_APP_DEPLOYMENT

      - name: Deploy to Azure
        run: |
          chmod +x deploy.sh
          ./deploy.sh